---
- name: Crear VLAN en Cisco SG350 usando comandos directos
  hosts: all
  gather_facts: no

  vars:
    vlan_id: 1200
    vlan_name: "Prueba1"

  tasks:
    - name: Entrar al modo configuración
      ansible.builtin.raw: configure terminal

    - name: Crear VLAN
      ansible.builtin.raw: vlan {{ vlan_id }}

    - name: Asignar nombre a la VLAN
      ansible.builtin.raw: name {{ vlan_name }}

    - name: Salir del modo de configuración
      ansible.builtin.raw: exit

    - name: Guardar configuración
      ansible.builtin.raw: write memory
