---
- name: Crear VLAN 1200 en Cisco SG350 por CLI
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli

  vars:
    ansible_network_os: cisco.ios.ios
    vlan_id: 1200
    vlan_name: prueba

  tasks:
    - name: Crear VLAN y asignar nombre
      ansible.netcommon.cli_config:
        config:
          - "vlan {{ vlan_id }}"
          - "name {{ vlan_name }}"
