---
- name: Crear VLAN en Cisco SG350 usando SSH puro
  hosts: all
  gather_facts: no

  vars:
    ssh_port: 11110
    vlan_id: 1200
    vlan_name: "Prueba1"

  tasks:
    - name: Crear VLAN usando SSH y comandos encadenados
      ansible.builtin.shell: |
        ssh -p {{ ssh_port }} -o StrictHostKeyChecking=no {{ ansible_user }}@{{ inventory_hostname }} /bin/bash << EOF
        enable
        configure terminal
        vlan {{ vlan_id }}
        name {{ vlan_name }}
        exit
        do write memory
        exit
        EOF
      args:
        executable: /bin/bash
