---
- name: Crear VLAN 1200 en SG350 por SSH puro
  hosts: all
  gather_facts: no

  tasks:
    - name: Enviar comandos para crear VLAN
      ansible.builtin.shell: |
        ssh -p {{ ansible_port | default(22) }} -o StrictHostKeyChecking=no {{ ansible_user }}@{{ inventory_hostname }} <<'EOF'
        configure terminal
        vlan 1200
        name prueba
        end
        write memory
        EOF
      args:
        executable: /bin/bash
