---
- name: Crear VLAN en Cisco SG350 usando SSH + expect
  hosts: all
  gather_facts: no

  vars:
    vlan_id: 1100
    vlan_name: "XYZ"

  tasks:
    - name: Crear VLAN vía expect
      ansible.builtin.expect:
        command: ssh -p 11110 {{ ansible_user }}@{{ inventory_hostname }}
        responses:
          (?i)password: "{{ ansible_password }}"
          "^>": "enable"
          "^#": "configure terminal"
          "\(config\)#": "interface vlan {{ vlan_id }}"
          "\(config-if\)#": "name {{ vlan_name }}"
          "\(config-if\)#": "exit"
          "\(config\)#": "do write memory"
          "\(Y/N\)": "Y"
          "^#": "exit"
      no_log: false
      timeout: 40
