---
- name: Crear VLAN en Cisco SG350 usando SSH puro y expect
  hosts: all
  gather_facts: no
  tasks:
    - name: Crear VLAN con nombre y guardar config
      ansible.builtin.expect:
        command: ssh -p 11110 {{ inventory_hostname }}
        responses:
          'Username:': "{{ ansible_user }}"
          'Password:': "{{ ansible_password }}"
          '>': "enable"
          '#': "configure terminal"
          '\(config\)#': "interface vlan 1100"
          '\(config-if\)#': "name XYZ"
          '\(config-if\)#': "exit"
          '\(config\)#': "do write memory"
          '\[startup-config\]\.\.\.\. \(Y/N\)': "Y"
          '\(config\)#': "exit"
          '#': "exit"
      no_log: true
