---
- name: Crear VLAN 1200 en SG350 (CORAL MANTA)
  hosts: all
  gather_facts: no

  vars:
    vlan_id: 1200
    vlan_name: PRUEBA

  tasks:
    - name: Crear VLAN y asignar nombre
      cisco.ios.ios_config:
        lines:
          - "vlan {{ vlan_id }}"
          - "name {{ vlan_name }}"
        save_when: never

    - name: Guardar configuracion (write memory)
      cisco.ios.ios_command:
        commands:
          - "write memory"
