---
- name: Crear VLAN en Cisco SG350 usando expect
  hosts: all
  gather_facts: no

  vars:
    vlan_id: 1200
    vlan_name: "Prueba1"

  tasks:
    - name: Crear VLAN usando expect
      ansible.builtin.expect:
        command: ssh -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -p {{ ansible_port }} {{ ansible_user }}@{{ inventory_hostname }}
        responses:
          'Password:': "{{ ansible_password }}"
          '>': "enable"
          '#': "configure terminal"
          '(config)#': "vlan {{ vlan_id }}"
          '(config-vlan)#': "name {{ vlan_name }}"
          '(config-vlan)#': "exit"
          '(config)#': "do write memory"
          '(config)#': "exit"
          '#': "exit"
      vars:
        ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
      no_log: false
