---
- name: "Crear VLAN 1200 en SG350 (CORAL MANTA)"
  hosts: all
  gather_facts: false

  vars:
    vlan_id: 1200
    vlan_name: PRUEBA

  tasks:
    - name: "Crear VLAN {{ vlan_id }} y asignar nombre"
      cisco.ios.ios_config:
        parents:
          - "vlan {{ vlan_id }}"
        lines:
          - "name {{ vlan_name }}"

    - name: "Guardar configuracion (write memory)"
      cisco.ios.ios_command:
        commands:
          - "write memory"
