---
- name: Crear VLAN en Cisco SG350 usando SSH puro
  hosts: all
  gather_facts: no

  vars:
    vlan_id: 1200
    vlan_name: "Prueba1"

  tasks:
    - name: Crear VLAN vía SSH (forzando ssh-rsa + terminal)
      ansible.builtin.shell: |
        ssh -tt -p {{ ansible_port }} \
        -o HostKeyAlgorithms=+ssh-rsa \
        -o KexAlgorithms=+diffie-hellman-group14-sha1 \
        -o StrictHostKeyChecking=no \
        {{ ansible_user }}@{{ inventory_hostname }} <<'EOF'
        enable
        configure terminal
        vlan {{ vlan_id }}
        name {{ vlan_name }}
        exit
        do write memory
        exit
        EOF
      args:
        executable: /bin/bash
      timeout: 30
