---
- name: Crear VLAN en Cisco SG350 usando SSH + expect
  hosts: all
  gather_facts: no
  vars:
    vlan_id: 1100           # Puedes sobrescribir esto desde AWX en "Variables"
    vlan_name: XYZ          # Lo mismo con este

  tasks:
    - name: Crear VLAN vía expect
      ansible.builtin.expect:
        command: ssh -p 11110 {{ inventory_hostname }}
        responses:
          '^.*#': 'conf t'
          '^.*\\(config\\)#': "int vlan {{ vlan_id }}"
          '^.*\\(config-if\\)#': "name {{ vlan_name }}"
          '^.*\\(config-if\\)#': "exit"
          '^.*\\(config\\)#': "do wr m"
          'Y/N': 'Y'
        timeout: 30
        echo: yes
      no_log: false
