- name: Crear VLAN en Cisco SG350 vía Netmiko desde AWX
  hosts: all
  gather_facts: no
  tasks:
    - name: Ejecutar script Python en el controlador (local)
      delegate_to: localhost
      vars:
        host_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      command: >
        python3 crear_vlan.py {{ host_ip }}
        {{ ansible_user }}
        {{ ansible_ssh_pass }}
        {{ ansible_port }}
        {{ vlan_id }} {{ nombre_vlan }}
