---
- name: Crear VLAN en Cisco SG350 (método net_connect)
  hosts: all
  gather_facts: no

  vars:
    vlan_id: 1200
    vlan_name: "Prueba1"

  tasks:
    - name: Conectar y ejecutar comandos de configuración
      ansible.netcommon.net_connect:
        connection: network_cli
        platform: cisco_smb
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        port: "{{ ansible_port | default(22) }}"
        commands:
          - configure terminal
          - vlan {{ vlan_id }}
          - name {{ vlan_name }}
          - exit
          - write memory
