---
- name: Crear VLAN 1200 en switches Cisco SG350
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Crear VLAN 1200 con nombre prueba (CLI)
      ansible.netcommon.cli_config:
        config: |
          vlan 1200
           name prueba
          exit

    - name: Guardar configuracion
      ansible.netcommon.cli_command:
        command: write memory
