---
- name: Backup startup-config a TFTP (TP-Link)
  hosts: all
  gather_facts: no

  vars:
    tftp_server: "192.168.57.11"

  tasks:
    - name: Ejecutar backup TP-Link por CLI (enable + copy startup-config tftp)
      ansible.builtin.command:
        argv:
          - python3
          - -u
          - /runner/project/TPLINK/backup_tftp_tplink.py
          - "{{ ansible_host }}"
          - "{{ ansible_user }}"
          - "{{ ansible_ssh_pass }}"
          - "{{ ansible_port | default('11110') }}"
          - "{{ tftp_server }}"
          - "{{ inventory_hostname }}__{{ ansible_host }}"
      delegate_to: localhost
      register: out

    - name: Mostrar salida del script
      ansible.builtin.debug:
        var: out.stdout

    - name: Mostrar log de sesión (últimas 250 líneas)
      ansible.builtin.shell: "ls -1t /tmp/tplink_backup_*.log 2>/dev/null | head -n 1 | xargs -r tail -n 250"
      delegate_to: localhost
      register: slog
      ignore_errors: yes

    - name: Debug session log
      ansible.builtin.debug:
        var: slog.stdout
