---
- name: Backup MikroTik por SSH y subir a SFTP (AWX) usando url=sftp://
  hosts: all
  gather_facts: no

  vars:
    sftp_host: "{{ sftp_host }}"
    sftp_port: "{{ sftp_port | default(22) }}"
    sftp_user: "{{ sftp_user }}"
    sftp_pass: "{{ sftp_pass }}"
    sftp_dir:  "{{ sftp_dir | default('upload') }}"

  tasks:
    - name: Generar timestamp
      ansible.builtin.set_fact:
        ts: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    - name: Normalizar carpeta SFTP (sin / al inicio o final)
      ansible.builtin.set_fact:
        sftp_dir_clean: "{{ sftp_dir | regex_replace('^/+','') | regex_replace('/+$','') }}"

    - name: Armar nombre base con hostname + IP + timestamp
      ansible.builtin.set_fact:
        ip_s: "{{ (ansible_host | default('NOIP')) | replace('.', '-') }}"
        base: "{{ inventory_hostname }}_{{ ip_s }}_{{ ts }}"

    - name: Crear backup binario en MikroTik (forzar salida)
      ansible.builtin.raw: '/system backup save name={{ base }}; :put "OK_BACKUP {{ base }}"; /quit'
      register: out_backup

    - name: Crear export texto en MikroTik (forzar salida)
      ansible.builtin.raw: '/export file={{ base }}; :put "OK_EXPORT {{ base }}"; /quit'
      register: out_export

    - name: Subir .backup por SFTP usando URL a carpeta upload/
      ansible.builtin.raw: >
        /tool fetch upload=yes
        url="sftp://{{ sftp_host }}:{{ sftp_port }}/{{ sftp_dir_clean }}/{{ base }}.backup"
        user="{{ sftp_user }}" password="{{ sftp_pass }}"
        src-path="{{ base }}.backup";
        :put "OK_UPLOAD_BACKUP {{ base }}"; /quit
      register: up_backup

    - name: Subir .rsc por SFTP usando URL a carpeta upload/
      ansible.builtin.raw: >
        /tool fetch upload=yes
        url="sftp://{{ sftp_host }}:{{ sftp_port }}/{{ sftp_dir_clean }}/{{ base }}.rsc"
        user="{{ sftp_user }}" password="{{ sftp_pass }}"
        src-path="{{ base }}.rsc";
        :put "OK_UPLOAD_RSC {{ base }}"; /quit
      register: up_rsc

    - name: Borrar archivos locales del MikroTik (opcional)
      ansible.builtin.raw: >
        /file remove "{{ base }}.backup";
        /file remove "{{ base }}.rsc";
        :put "OK_CLEAN {{ base }}"; /quit
      register: out_clean

    - name: Mostrar salidas clave
      ansible.builtin.debug:
        msg:
          - "{{ out_backup.stdout | default('') }}"
          - "{{ out_export.stdout | default('') }}"
          - "{{ up_backup.stdout | default('') }}"
          - "{{ up_rsc.stdout | default('') }}"
          - "{{ out_clean.stdout | default('') }}"
