---
- name: Crear usuario en MikroTik (AWX)
  hosts: all
  gather_facts: no

  vars:
    mt_user: "{{ mt_user }}"
    mt_pass: "{{ mt_pass }}"
    mt_group: "{{ mt_group | default('full') }}"

  tasks:
    - name: Crear usuario si no existe
      ansible.builtin.raw: >
        :if ([:len [/user find name="{{ mt_user }}"]] = 0) do={
          /user add name="{{ mt_user }}" password="{{ mt_pass }}" group="{{ mt_group }}";
          :put ("OK_USER_CREATED {{ mt_user }}");
        } else={
          :put ("OK_USER_EXISTS {{ mt_user }}");
        };
        /quit
      register: out_user

    - name: Mostrar resultado
      ansible.builtin.debug:
        var: out_user.stdout
