---
- name: Buscar MAC por Torch en todas las interfaces (devuelve interfaz)
  hosts: all
  gather_facts: no

  tasks:
    - name: Normalizar MAC
      ansible.builtin.set_fact:
        mac_u: "{{ mac | upper }}"
        watch_s: "{{ watch_seconds | default(10) }}"

    - name: Obtener lista de interfaces (ether/vlan/wlan/bridge)
      ansible.builtin.raw: ':put "IFLIST"; /interface print without-paging where disabled=no; /quit'
      register: if_out

    - name: Parsear nombres de interfaces
      ansible.builtin.set_fact:
        if_names: >-
          {{
            (if_out.stdout | default(''))
            | regex_replace('\\x1B\\[[0-9;]*[A-Za-z]', '')
            | regex_findall('name=([^\\s]+)')
          }}

    - name: Torch corto por interfaz ({{ watch_s }}s) para ver dónde aparece la MAC
      ansible.builtin.raw: >
        :local M "{{ mac_u }}";
        :local I "{{ item }}";
        :local T {{ watch_s }};
        :put ("--- TORCH iface=" . $I . " ---");
        /tool torch interface=$I duration=$T;
        /quit
      loop: "{{ if_names }}"
      register: torch_all
      failed_when: false

    - name: Detectar interfaces candidatas (si la MAC aparece en el output)
      ansible.builtin.set_fact:
        mac_hits: >-
          {{
            torch_all.results
            | selectattr('stdout','defined')
            | selectattr('stdout','search', mac_u)
            | map(attribute='item')
            | list
          }}

    - name: Resultado final (interfaces donde se vio la MAC)
      ansible.builtin.debug:
        msg:
          - "MAC: {{ mac_u }}"
          - "Interfaces donde se observó (Torch): {{ mac_hits | default([]) }}"
