---
- name: Buscar MAC y mostrar puerto en MikroTik (AWX)
  hosts: all
  gather_facts: no

  tasks:
    - name: Normalizar MAC
      ansible.builtin.set_fact:
        mac_u: "{{ mac | upper }}"

    - name: Tabla MAC - Bridge Host (detail)
      ansible.builtin.raw: ':put "BRIDGE_HOST_DETAIL"; /interface bridge host print detail where mac-address={{ mac_u }}; /quit'
      register: bh_detail

    - name: ARP (si existe)
      ansible.builtin.raw: ':put "ARP_DETAIL"; /ip arp print detail where mac-address={{ mac_u }}; /quit'
      register: arp_detail
      failed_when: false

    - name: DHCP Lease (si existe)
      ansible.builtin.raw: ':put "DHCP_LEASE_DETAIL"; /ip dhcp-server lease print detail where active-mac-address={{ mac_u }}; /quit'
      register: lease_detail
      failed_when: false

    # Limpieza de ANSI (colores) para que regex funcione bien
    - name: Limpiar salida bridge host (quitar ANSI)
      ansible.builtin.set_fact:
        bh_clean: "{{ (bh_detail.stdout | default('')) | regex_replace('\\x1B\\[[0-9;]*[A-Za-z]', '') }}"

    - name: Extraer puerto/interfaz (on-interface o interface)
      ansible.builtin.set_fact:
        mac_port: >-
          {{
            (bh_clean | regex_search('on-interface=([^\\s]+)', '\\1'))
            or (bh_clean | regex_search('interface=([^\\s]+)', '\\1'))
            or 'NO_ENCONTRADO'
          }}

    - name: Resumen claro (PUERTO + IP si existe)
      ansible.builtin.debug:
        msg:
          - "MAC: {{ mac_u }}"
          - "PUERTO/INTERFAZ (bridge host): {{ mac_port }}"
          - "--- RAW BRIDGE HOST ---"
          - "{{ bh_detail.stdout | default('') }}"
          - "--- RAW ARP ---"
          - "{{ arp_detail.stdout | default('') }}"
          - "--- RAW DHCP LEASE ---"
          - "{{ lease_detail.stdout | default('') }}"
