---
- name: Buscar MAC y mostrar puerto en MikroTik (AWX)
  hosts: all
  gather_facts: no

  tasks:
    - name: Normalizar MAC
      ansible.builtin.set_fact:
        mac_u: "{{ mac | upper }}"

    - name: Buscar MAC y mostrar puerto (bridge host / fallback)
      ansible.builtin.raw: >
        :local M "{{ mac_u }}";
        :put "==============================";
        :put ("MAC BUSCADA: " . $M);
        :put "==============================";

        :put "--- BRIDGE HOST (detalle) ---";
        :do {
          /interface bridge host print detail
            where mac-address=$M;
        } on-error={ :put "BRIDGE HOST: no disponible" };

        :put "--- BRIDGE HOST (simple) ---";
        :do {
          /interface bridge host print
            where mac-address=$M;
        } on-error={ :put "BRIDGE HOST simple: no disponible" };

        :put "--- ARP (si tiene IP) ---";
        :do {
          /ip arp print detail
            where mac-address=$M;
        } on-error={ :put "ARP: no disponible" };

        :put "--- DHCP LEASE (si aplica) ---";
        :do {
          /ip dhcp-server lease print detail
            where active-mac-address=$M;
        } on-error={ :put "DHCP LEASE: no disponible" };

        /quit
      register: out

    - name: Imprimir salida
      ansible.builtin.debug:
        var: out.stdout
